#!/bin/bash
# BT Dev Machine Set up

mkdir artifacts

# Brew

if ! which brew >/dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew update

# fish
./fish

# rando basics
./basics.fish

# asdf managed packages
./asdf.fish

# kubernetes tools
./k8s.fish

./github-subscriber.fish
