#!/bin/bash

if ! which fish >/dev/null; then
    sudo apt-add-repository ppa:fish-shell/release-3 -y
    sudo apt update -y
    sudo apt install fish -y

    # init fish config
    mkdir ~/.config
    mkdir ~/.config/fish
    touch ~/.config/fish/config.fish
fi

# fisher
curl -sL https://git.io/fisher > artifacts/fisherinstall

# plugins
fish artifacts/fisherinstall

